version: '3.8'

services:
  app:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chatbot
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
